# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: arangodb
  namespace: fraudblok-development
  labels:
    app.kubernetes.io/instance: arango
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: arango
type: Opaque
data:
  root-password: {{ .Values.arangodb.authentication.rootPassword | b64enc | quote }}
