# SPDX-License-Identifier: Apache-2.0

{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

controller:
  admissionWebhooks:
    certManager:
      enabled: true
  service:
    type: ClusterIP
