# SPDX-License-Identifier: Apache-2.0

{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP
  extraModules:
    - name: opentelemetry
      image:
        registry: registry.k8s.io
        image: busybox
        tag: latest
