apiVersion: v1
entries:
  apm-server:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2025-02-17T14:20:05.4195398+02:00"
    description: Official Elastic helm chart for Elastic APM Server
    digest: 64682ed730f3448dd1cdbe449449f2e5f9ee897535cdc6402d527a832a8e9168
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/apm.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: apm-server
    sources:
    - https://github.com/elastic/apm
    urls:
    - https://btzrmn.github.io/tz-helm/charts/apm-server-8.5.1.tgz
    version: 8.5.1
  arangodb:
  - apiVersion: v2
    created: "2025-02-17T14:20:05.4213392+02:00"
    digest: 244f65b20c698ea2f440e9451adfc3d0e2fff0c041de3346b337aaf39956e3be
    name: arangodb
    urls:
    - https://btzrmn.github.io/tz-helm/charts/arangodb-1.0.0.tgz
    version: 1.0.0
  elasticsearch:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2025-02-17T14:20:05.4220392+02:00"
    description: Official Elastic helm chart for Elasticsearch
    digest: 5fd178f2d96771386367d1ed14f7d6b6d80549979eb10c26ba433376be8d3be2
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/elasticsearch.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: elasticsearch
    sources:
    - https://github.com/elastic/elasticsearch
    urls:
    - https://btzrmn.github.io/tz-helm/charts/elasticsearch-8.5.1.tgz
    version: 8.5.1
  grafana:
  - annotations:
      artifacthub.io/license: AGPL-3.0-only
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 10.0.3
    created: "2025-02-17T14:20:05.4241345+02:00"
    description: The leading tool for querying and visualizing time series and metrics.
    digest: 91cafb1365796a2f75f7be22cf94f1f74e3ec794e9d5b1214432a229716ae3eb
    home: https://grafana.net
    icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - https://btzrmn.github.io/tz-helm/charts/grafana-6.58.8.tgz
    version: 6.58.8
  infra-chart:
  - apiVersion: v2
    created: "2025-02-17T14:20:05.4251352+02:00"
    description: A Helm chart for installing infrastructure components for the FRMS
      system.
    digest: 588e6bd045e650a0abf9686750077da994772aaf4ba31c8620d05feede6327a2
    name: infra-chart
    type: application
    urls:
    - https://btzrmn.github.io/tz-helm/charts/infra-chart-1.0.0.tgz
    version: 1.0.0
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: |-
        - "update web hook cert gen to latest release v20231226-1a7112e06"
        - "Update Ingress-Nginx version controller-v1.9.6"
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.9.6
    created: "2025-02-17T14:20:05.427536+02:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 251ee144c6b9cf224e057ab9dc5e2b4094d5f4d219fbd0786abaa31925472b5f
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.20.0-0'
    maintainers:
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - https://btzrmn.github.io/tz-helm/charts/ingress-nginx-4.9.1.tgz
    version: 4.9.1
  jenkins:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - Update `docker.io/kiwigrid/k8s-sidecar` to version `docker.io/kiwigrid/k8s-sidecar`
      artifacthub.io/images: |
        - name: jenkins
          image: docker.io/jenkins/jenkins:2.426.3-jdk17
        - name: k8s-sidecar
          image: docker.io/kiwigrid/k8s-sidecar:1.25.4
        - name: inbound-agent
          image: jenkins/inbound-agent:3206.vb_15dcf73f6a_9-3
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
        - name: Jenkins
          url: https://www.jenkins.io/
        - name: support
          url: https://github.com/jenkinsci/helm-charts/issues
    apiVersion: v2
    appVersion: 2.426.3
    created: "2025-02-17T14:20:05.4312107+02:00"
    description: Jenkins - Build great things at any scale! The leading open source
      automation server, Jenkins provides over 1800 plugins to support building, deploying
      and automating any project.
    digest: f9c68f5d1faa92254a793ac3dc53db26ea84f4d00e21a06913d7a8d402ee9ea7
    home: https://jenkins.io/
    icon: https://get.jenkins.io/art/jenkins-logo/logo.svg
    keywords:
    - jenkins
    - ci
    - devops
    maintainers:
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: garridomota@gmail.com
      name: mogaal
    - email: wmcdona89@gmail.com
      name: wmcdona89
    - email: timjacomb1@gmail.com
      name: timja
    name: jenkins
    sources:
    - https://github.com/jenkinsci/jenkins
    - https://github.com/jenkinsci/docker-inbound-agent
    - https://github.com/maorfr/kube-tasks
    - https://github.com/jenkinsci/configuration-as-code-plugin
    urls:
    - https://btzrmn.github.io/tz-helm/charts/jenkins-5.0.13.tgz
    version: 5.0.13
  keycloak:
  - annotations:
      category: DeveloperTools
      images: |
        - name: keycloak-config-cli
          image: docker.io/bitnami/keycloak-config-cli:5.10.0-debian-11-r0
        - name: keycloak
          image: docker.io/bitnami/keycloak:23.0.3-debian-11-r0
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 23.0.3
    created: "2025-02-17T14:20:05.4371104+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 13.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Keycloak is a high performance Java-based identity and access management
      solution. It lets developers add an authentication layer to their applications
      with minimum effort.
    digest: 19981700a399ec4a9a1830223fe22e3e958f313883f0dea8fe42136419afb987
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/keycloak/img/keycloak-stack-220x234.png
    keywords:
    - keycloak
    - access-management
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: keycloak
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/keycloak
    urls:
    - https://btzrmn.github.io/tz-helm/charts/keycloak-18.0.0.tgz
    version: 18.0.0
  kibana:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2025-02-17T14:20:05.4381111+02:00"
    description: Official Elastic helm chart for Kibana
    digest: debc7580502fd575e5ee3aba4f47187f793655e22ba345f086201a38e4aa00f2
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/kibana.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: kibana
    sources:
    - https://github.com/elastic/kibana
    urls:
    - https://btzrmn.github.io/tz-helm/charts/kibana-8.5.1.tgz
    version: 8.5.1
  logstash:
  - apiVersion: v1
    appVersion: 8.5.1
    created: "2025-02-17T14:20:05.4391102+02:00"
    description: Official Elastic helm chart for Logstash
    digest: 90ca7287a5b0f6df4b8ea2ebca9dcaf89c7baf8ff782050f9721ebeb45019ca8
    home: https://github.com/elastic/helm-charts
    icon: https://helm.elastic.co/icons/logstash.png
    maintainers:
    - email: helm-charts@elastic.co
      name: Elastic
    name: logstash
    sources:
    - https://github.com/elastic/logstash
    urls:
    - https://btzrmn.github.io/tz-helm/charts/logstash-8.5.1.tgz
    version: 8.5.1
  nats:
  - apiVersion: v2
    appVersion: 2.9.19
    created: "2025-02-17T14:20:05.4401106+02:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: f311c12d8445528350582861c4266026dcae04c7ca7e87095dde1a00fb1eaf8f
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - https://btzrmn.github.io/tz-helm/charts/nats-0.19.16.tgz
    version: 0.19.16
  prometheus:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus/prometheus
    apiVersion: v2
    appVersion: v2.46.0
    created: "2025-02-17T14:20:05.4454924+02:00"
    dependencies:
    - condition: alertmanager.enabled
      name: alertmanager
      repository: https://prometheus-community.github.io/helm-charts
      version: 0.33.*
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.10.*
    - condition: prometheus-node-exporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.21.*
    - condition: prometheus-pushgateway.enabled
      name: prometheus-pushgateway
      repository: https://prometheus-community.github.io/helm-charts
      version: 2.4.*
    description: Prometheus is a monitoring system and time series database.
    digest: e3577c7271488266916483de15bb39ce81889a4b86631fdf94e747ebba0dbffe
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - monitoring
    - prometheus
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: naseem@transit.app
      name: naseemkullah
    - email: rootsandtrees@posteo.de
      name: zeritti
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    type: application
    urls:
    - https://btzrmn.github.io/tz-helm/charts/prometheus-23.2.0.tgz
    version: 23.2.0
  vault:
  - annotations:
      charts.openshift.io/name: HashiCorp Vault
    apiVersion: v2
    appVersion: 1.13.1
    created: "2025-02-17T14:20:05.449545+02:00"
    description: Official HashiCorp Vault Chart
    digest: 2bfbfd89825d3454e1989ae698f68067f2eb1e7c7752db4dcb71290ba91573c6
    home: https://www.vaultproject.io
    icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png
    keywords:
    - vault
    - security
    - encryption
    - secrets
    - management
    - automation
    - infrastructure
    kubeVersion: '>= 1.22.0-0'
    name: vault
    sources:
    - https://github.com/hashicorp/vault
    - https://github.com/hashicorp/vault-helm
    - https://github.com/hashicorp/vault-k8s
    - https://github.com/hashicorp/vault-csi-provider
    urls:
    - https://btzrmn.github.io/tz-helm/charts/vault-0.24.0.tgz
    version: 0.24.0
generated: "2025-02-17T14:20:05.4185051+02:00"
